//EJEMPLO 1 UTILIZANDO NestJs (CLASE 45)//

/*

AL CREAR UNA APLICACION NestJs CON EL COMANDO "nest new <nombre de carpeta>", SE CREAN VARIAS CARPETAS y ARCHIVOS:

(node_modules) CARPETA QUE CONTIENE LAS DEPENDENCIAS INSTALADAS EN LA APLICACION.
(src) src CARPETA DONDE SE ESCRIBE EL CODIGO FUENTE DE LA APLICACION.
(src/app.module.ts) ARCHIVO DONDE SE DEFINE EL MODULO RAIZ DE LA APLICACION.
(src/main.ts) ARCHIVO QUE INICIA LA APLICACION.
(src/app.controller.ts) ARCHIVO DONDE SE DEFINE UN CONTROLADOR BASICO PARA LA APLICACION.
(src/app.service.ts) ARCHIVO DONDE SE DEFINE UN SERVICIO BASICO PARA LA APLICACION.
(test) CARPETA DONDE SE ESCRIBEN LOS ARCHIVOS DE PRUEBA.
(test/app.e2e-spec.ts) ARCHIVO DONDE SE ESCRIBEN PRUEBAS DE INTEGRACION PARA LA APLICACION.
(test/jest-e2e.json) ARCHIVO DE CONFIGURACION PARA LAS PRUEBAS DE INTEGRACIÓN.
(tsconfig.json) ARCHIVO DE CONFIGURACION PARA TypeScript.
(package.json) ARCHIVO DONDE SE ESPECIFICAN LAS DEPENDENCIAS y SCRIPTS DE LA APLICACION.
(package-lock.json) ARCHIVO QUE BLOQUEA LAS VERSIONES DE LAS DEPENDENCIAS INSTALADAS.
(README.md) ARCHIVO DE DOCUMENTACION DE LA APLICACION.

*/
