//DESAFIO GENERICO - IMPLEMENTANDO DOTENV//

//TENGO QUE REALIZAR LO MISMO QUE EL DESAFIO ANTERIOR PARA ESTA VEZ USANDO LA LIBERIA dotenv//

//IMPORTO express PARA PODER UTILIZARLO//
import express from 'express';
const app = express();

//IMPORTO configuracion.js DESDE LA CARPETA config PARA PODER UTILIZARLO//
import configuracion from './config/configuracion.js';

const PUERTO = configuracion.app.PUERTO; //ANTES ME DECIA QUE EL PUERTO LO TOME DESDE process.env.PUERTO, PERO AHORA VAMOS A DECIRLE QUE LO TOME DE MI APLICATIVO GENERAL, MEDIANTE LA IMPORTACION DE configuracion.js
app.listen(PUERTO, ()=>console.log(`Servidor escuchandose en http://localhost:${PUERTO}`));


//BASICAMENTE, dotenv ES UN MODULO DE Node QUE CARGA VARIABLES DE ENTORNO DESDE UN ARCHIVO .env a process.env//
//EL DESARROLLO CON MULTIPLES VARIABLES DE ENTORNO SE VUELVE RAPIDAMENTE DIFICIL DE MANTENER. ENTONCES, UTILIZAMOS dotenv PARA QUE LAS VARIABLES QUEDEN ALMACENADAS TODAS JUNTAS EN EL ARCHIVO .env//
