//DESAFIO GENERICO - COLOR ALEATORIO CON BABEL//

//TENGO QUE REALIZAR UN PROGRAMA QUE GENERE UN COLOR ALEATORIO EN FORMATO RGB y LO MUESTRE POR CONSOLA. ESTE ESTARA IMPLEMENTADO EN UN ARCHIVO LLAMADO color.js//
//LA FUNCIONALIDAD DEBE ESTAR IMPLEMENTADA DENTRO DE UNA CLASE y DEBERA UTILIZAR SINTAXIS ES6 (const, let, arrow functions y template string)
//CONVERTIR ESTE CODIGO ES6 a JS5 CON BABEL ONLINE. REALIZAR ESTA CONVERSION EN FORMA AUTOMATICA DENTRO DE UN PROYECTO node.js QUE UTILICE BABEL CLI//

//CREO UNA VARIABLE LLAMADA getNumeroAleatorio LA CUAL ME RETORNA MEDIANTE UN RETURN IMPLICITO Math.floor(Math.random() * maximoNumero) LA CUAL NOS TRAE UN NUMERO ALEATORIO//
let getNumeroAleatorio = (maximoNumero)=> Math.floor(Math.random() * maximoNumero);

//CREO UNA CLASE LLAMADA Color//
class Color{

    //CREO EL METODO get LA CUAL VA A OBTENER EL COLOR ALEATORIO EN RGB//
    get(){
        return `RGB(${getNumeroAleatorio(255)}, ${getNumeroAleatorio(255)}, ${getNumeroAleatorio(255)}, 1)`;
    }
}

//CREO LA INSTANCIA DE LA CLASE Color//
const color = new Color()
console.log(`EL COLOR ALEATORIO ES ${color.get()}`);