//DESAFIO GENERICO - USUARIO 'ENCARGADO'//

//(PUNTO 1)//
//CREAR UN USUARIO QUE ACCEDA CON NOMBRE 'encargado' y CLAVE 'qwerty123' SOLO A LA BASE 'empresa' y TENGA PERMISOS DE LECTURA y ESCRITURA//
db.createUser({"user":"encargado", "pwd":"qwerty123", "roles":["readWrite"]})

//(PUNTO 2)//
//ACCEDER CON ESE USUARIO y LISTAR DE LA COLECCION CLIENTES SOLO LOS NOMBRES DE LOS MISMOS//

//(PUNTO 3)//
//VERIFICAR QUE NO PUEDA ACCEDER SI SUS CREDENCIALES NO CORRESPONDEN//